import {test,expect } from "@playwright/test"
test.beforeEach(async ({ page }) => {
  await page.goto("https://groceryapp.uniqassosiates.com/admin")
})
test.only('Edit Contact',async({page})=>{
    test.setTimeout(60000)
    const username= page.locator("//input[@name='username']")
    await username.fill('admin')
    const password= page.locator("//input[@name='password']")
    await password.fill('admin')
    const signinbutton=page.locator("//button[@type='submit']")
    await signinbutton.click()
    const pagetitle= await page.title()
    console.log(pagetitle)
    await expect(page).toHaveTitle('Dashboard | 7rmart supermarket')
    //const managecontact=page.locator("//a[@class=' nav-link']").nth(0)
    //await managecontact.click()
    const moreinfofooter= page.locator(".small-box-footer").nth(2)
    await moreinfofooter.click()
    const contactpagetitle= await page.title()
    console.log(contactpagetitle)
    await expect(page).toHaveTitle('Contact Us | 7rmart supermarket')
    const editicon=page.locator("//a[@role='button']")
    await editicon.click()
    await expect(page).toHaveTitle('Contact Us | 7rmart supermarket')
    const phonenumber= page.locator("#phone")
    await phonenumber.fill('123456789')
    const email= page.locator("#email")
    await email.fill('varnatest@gmail.com')
    const address= page.locator("//textarea[@name='address']")
    await address.fill('test adress for Varna')
    const deliverytime= page.locator("//textarea[@name='del_time']")
    await deliverytime.fill('5PM for Varna')
    const deliverychargelimit=page.locator("//input[@name='del_limit']")
    await deliverychargelimit.fill('100 for Varna')
    const updatebutton= page.locator("//button[@name='Update']")
    await updatebutton.click()
    //await expect(page.getByText(' Alert!')).toBeVisible()
    //await expect(page.getByText('            Contact Updated Successfully        ')).toBeVisible()
  const alertbox= page.locator("//div[@class='alert alert-success alert-dismissible']")
  const successmessage= await alertbox.textContent()
   console.log(successmessage)
   await expect(successmessage).toContain('Contact Updated Successfully')

})
